[tools]
rojo = { source = "rojo-rbx/rojo", version = "=7.4.0" }
selene = { source = "Kampfkarren/selene", version = "=0.25.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "=0.18.1" }
wally = { github = "UpliftGames/wally", version = "=0.3.2" }
luau-lsp = { github = "johnnymorganz/luau-lsp", version = "=1.27.1"}
run-in-roblox = { github = "rojo-rbx/run-in-roblox", version = "=0.3.0" }
darklua = { github = "seaofvoices/darklua", version = "=0.14.0" }
